import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Layout from '../components/layout'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>qlub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>TOP PAGE</h1>
      </Layout>
    </div>
  )
}
